CC		=	gcc
CFLAGS  =   -I../../allegro/allegro4/include -I./mpq
LIBS    =   ../../allegro/allegro4/lib/*.a -lm -lpthread -lX11 -lXcursor -lXcursor -ldl
OBJS    =   ./mpq/dcl_tbl.o ./mpq/explode.o ./mpq/mpqview.o ./mpq/wav_unp.o anim.o animdata.o dc6info.o dccinfo.o ds1misc.o ds1save.o dt1_draw.o dt1misc.o editobj.o editpath.o edittile.o error.o gfx_custom.o inicreat.o iniread.o interfac.o main.o misc.o msg_quit.o msg_save.o txtread.o undo.o wbits.o wedit.o wmsg.o wpreview.o
all:$(OBJS)
	$(CC) -w -g $(OBJS)  $(CFLAGS) $(LIBS) -o ../bin/mapedit
test:
	make test -C ../bin
debug:
	make debug -C ../bin
clean:
	rm  *.o ./mpq/*.o ../bin/mapedit -f
dcl_tbl.o:./mpq/dcl_tbl.c
	$(CC) -w -g -c $(CFLAGS)  ./mpq/dcl_tbl.c -o ./mpq/dcl_tbl.o
explode.o:./mpq/explode.c
	$(CC) -w -g -c $(CFLAGS)  ./mpq/explode.c -o ./mpq/explode.o
mpqview.o:./mpq/mpqview.c
	$(CC) -w -g -c $(CFLAGS)  ./mpq/mpqview.c -o ./mpq/mpqview.o
wav_unp.o:./mpq/wav_unp.c
	$(CC) -w -g -c $(CFLAGS)  ./mpq/wav_unp.c -o ./mpq/wav_unp.o
anim.o:anim.c
	$(CC) -w -g -c $(CFLAGS)  anim.c
animdata.o:animdata.c
	$(CC) -w -g -c $(CFLAGS)  animdata.c
dc6info.o:dc6info.c
	$(CC) -w -g -c $(CFLAGS)  dc6info.c
dccinfo.o:dccinfo.c
	$(CC) -w -g -c $(CFLAGS)  dccinfo.c
ds1misc.o:ds1misc.c
	$(CC) -w -g -c $(CFLAGS)  ds1misc.c
ds1save.o:ds1save.c
	$(CC) -w -g -c $(CFLAGS)  ds1save.c
dt1_draw.o:dt1_draw.c
	$(CC) -w -g -c $(CFLAGS)  dt1_draw.c
dt1misc.o:dt1misc.c
	$(CC) -w -g -c $(CFLAGS)  dt1misc.c
editobj.o:editobj.c
	$(CC) -w -g -c $(CFLAGS)  editobj.c
editpath.o:editpath.c
	$(CC) -w -g -c $(CFLAGS)  editpath.c
edittile.o:edittile.c
	$(CC) -w -g -c $(CFLAGS)  edittile.c
error.o:error.c
	$(CC) -w -g -c $(CFLAGS)  error.c
gfx_custom.o:gfx_custom.c
	$(CC) -w -g -c $(CFLAGS)  gfx_custom.c
inicreat.o:inicreat.c
	$(CC) -w -g -c $(CFLAGS)  inicreat.c
iniread.o:iniread.c
	$(CC) -w -g -c $(CFLAGS)  iniread.c
interfac.o:interfac.c
	$(CC) -w -g -c $(CFLAGS)  interfac.c
main.o:main.c
	$(CC) -w -g -c $(CFLAGS)  main.c
misc.o:misc.c
	$(CC) -w -g -c $(CFLAGS)  misc.c
msg_quit.o:msg_quit.c
	$(CC) -w -g -c $(CFLAGS)  msg_quit.c
msg_save.o:msg_save.c
	$(CC) -w -g -c $(CFLAGS)  msg_save.c
txtread.o:txtread.c
	$(CC) -w -g -c $(CFLAGS)  txtread.c
undo.o:undo.c
	$(CC) -w -g -c $(CFLAGS)  undo.c
wbits.o:wbits.c
	$(CC) -w -g -c $(CFLAGS)  wbits.c
wedit.o:wedit.c
	$(CC) -w -g -c $(CFLAGS)  wedit.c
wmsg.o:wmsg.c
	$(CC) -w -g -c $(CFLAGS)  wmsg.c
wpreview.o:wpreview.c
	$(CC) -w -g -c $(CFLAGS)  wpreview.c
